name = "ghost-meilisearch-webhook-handler"
main = "apps/webhook-handler/dist/worker.js"
compatibility_date = "2023-10-30"

[vars]
# These are example environment variables
# WEBHOOK_SECRET = ""
# GHOST_MEILISEARCH_CONFIG = ""

# Trigger builds on push to main branch
[triggers]
crons = []

# Configure routes - removed as they're not needed for simple Workers
# Routes are configured in the Cloudflare dashboard

# Configure build
[build]
command = "npm run build:webhook"
